#!/usr/bin/expect                                                                                                                      
set timeout 5
if { [llength $argv] < 1} {
  puts "Usage:"
  puts "$argv0 hostname"
  exit 1
}
set hostname [lindex $argv 0]
spawn ssh -vvv $hostname
expect "*10.33.101.152's password:" { send "file_password1\r" }
expect "*Input target server username:" { send "name\r" }
expect "*Input target server password:" { send "password\r" }
interact
